### ISSUE TITLE
Problema con el historico de los mensajes

### ISSUE THREAD

**Issue by joseda92** [joseda92/odoo#1]
Cuando voy a configuración, y pulso en history SMS me aparece el siguiente error

Traceback (most recent call last):
  File "/opt/odoo/server/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/server/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/server/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/server/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/server/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/server/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/server/openerp/addons/web/controllers/main.py", line 876, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/opt/odoo/server/openerp/addons/web/controllers/main.py", line 897, in do_search_read
    request.context)
  File "/opt/odoo/server/openerp/http.py", line 900, in proxy
    result = meth(cr, request.uid, _args, *_kw)
  File "/opt/odoo/server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/server/openerp/models.py", line 5127, in search_read
    result = self.read(cr, uid, record_ids, fields, context=read_ctx)
  File "/opt/odoo/server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/server/openerp/models.py", line 3125, in read
    result = BaseModel.read(records, fields, load=load)
  File "/opt/odoo/server/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/server/openerp/models.py", line 3171, in read
    values[name] = field.convert_to_read(record[name], use_name_get)
  File "/opt/odoo/server/openerp/models.py", line 5554, in **getitem**
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/server/openerp/fields.py", line 817, in **get**
    self.determine_value(record)
  File "/opt/odoo/server/openerp/fields.py", line 919, in determine_value
    self.compute_value(recs)
  File "/opt/odoo/server/openerp/fields.py", line 875, in compute_value
    self._compute_value(records)
  File "/opt/odoo/server/openerp/fields.py", line 867, in _compute_value
    self.compute(records)
  File "/opt/odoo/server/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/server/openerp/api.py", line 397, in new_api
    result = [method(rec, _args, *_kwargs) for rec in self]
  File "/opt/odoo/server/openerp/addons/entity_sms/esms_history.py", line 32, in _rec_nam
    my_record = self.env[self.model_id.model].search([('id','=',self.record_id)])
  File "/opt/odoo/server/openerp/api.py", line 721, in __getitem__
    return self.registry[model_name]._browse(self, ())
  File "/opt/odoo/server/openerp/modules/registry.py", line 102, in __getitem__
    return self.models[model_name]
KeyError: False

**Comment by edanpiro** [comment]
Realiza nuevas pruebas y me avisas para cerrrar esta tarea

**Comment by joseda92** [comment]
Resuelta
